import React from "react";

const InterviewReport = ({ data }) => {
  const {
    finalScore,
    confidence,
    communication,
    correctness,
    questionWiseScore,
  } = data;

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-lg p-6 space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-gray-800">
            Interview Report
          </h1>
          <p className="text-gray-500 text-sm">
            AI-generated performance analysis
          </p>
        </div>

        {/* Scores */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[{ label: "Final Score", value: finalScore },
            { label: "Confidence", value: confidence },
            { label: "Communication", value: communication },
            { label: "Correctness", value: correctness }].map((item, idx) => (
            <div
              key={idx}
              className="bg-gray-50 p-4 rounded-xl text-center border"
            >
              <p className="text-sm text-gray-500">{item.label}</p>
              <p className="text-xl font-semibold text-gray-800">
                {item.value}
              </p>
            </div>
          ))}
        </div>

        {/* Question-wise Feedback */}
        <div>
          <h2 className="text-lg font-semibold text-gray-800 mb-3">
            Question-wise Analysis
          </h2>

          <div className="space-y-4">
            {questionWiseScore.map((q, index) => (
              <div
                key={index}
                className="border rounded-xl p-4 bg-gray-50"
              >
                <p className="font-medium text-gray-800">
                  Q{index + 1}. {q.question}
                </p>

                <div className="flex flex-wrap gap-4 mt-2 text-sm">
                  <span className="text-blue-600">
                    Score: {q.score}
                  </span>
                  <span className="text-green-600">
                    Confidence: {q.confidence}
                  </span>
                </div>

                <p className="text-gray-600 mt-2">
                  {q.feedback}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-sm text-gray-400">
          Generated by AI Interview System
        </div>
      </div>
    </div>
  );
};

export default InterviewReport;
